// let orderPromise= require ("./1-Promise-Object.js")
// console.log(orderPromise)
// require("./2-setTimeout-Function.js")
// require("./3-onFulfilled-and-onRejected-Functions.js")
// require("./4-catch-Function.js")
require("./5-Chaining-Multiple-Promises.js")
// require("./6-Common-Mistakes.js")
// require("./7-promiseAll-Funciton.js")
